tests/test_phonopy.py
wfl/cli/gap_rss_iter_fit.py
wfl/fit/ace.py
wfl/fit/gap_multistage.py
wfl/fit/gap_simple.py
wfl/fit/utils.py
wfl/generate_configs/phonopy.py
wfl/pipeline/remote.py
wfl/pipeline/utils.py

Add support for passing timeout to `ExPyRe.get_results()`, rather than the hardwired default of 3600 s.  Also work around phono3py bug (perhaps now fixed in https://github.com/phonopy/phono3py/pull/65) by always using phonopy (rather than phono3py) for harmonic force constant (phonon) displacements.

set timeout for remote jobs, and fix phonopy displacement generation

---

README.md
complete_pytest
tests/calculators/test_qe.py
tests/test_configset_in.py
tests/test_minim.py
tests/test_ref_error.py
wfl/calculators/espresso.py
wfl/fit/ace.py
wfl/fit/gap_multistage.py
wfl/fit/gap_simple.py
wfl/fit/ref_error.py
wfl/fit/utils.py
wfl/generate_configs/buildcell.py
wfl/generate_configs/minim.py
wfl/generate_configs/supercells.py
wfl/utils/find_voids.py

Fix and standardize handling of remote_info in ace, gap_simple, and gap_multistage fitting wrappers
[ADDED LATER]
Fix some failing tests (not related to initial `remote_info` focus)
Fix some deprecated syntax, mainly spglib.

Fix bugs in handling of remote_info for local and remote jobs that do fitting

---

tests/calculators/test_qe.py
wfl/pipeline/remote.py
wfl/pipeline/utils.py

New field,  `header_extra`, in `RemoteInfo` structure, which is passed to `ExPyRe.start()`. 
Note that this PR is currently based on the ACE1 patch, which will therefore need to be merged first (or something will have to be rebased).

Per remote job header

---

wfl/fit/ace.py
wfl/fit/gap_multistage.py
wfl/fit/gap_simple.py

Add header_extra to other calls to ExPyRe.start(), namely in `wfl/fit/{ace,gap}*py`.  Maybe this should be made more automatic somehow?

More places where header_extra needs to be passed.

---

wfl/cli/cli.py

Extract contents of cli descriptor calculation into its own non-decorated function, which can be called from the cli descriptor calc command, and also be optionally called from the cli command for doing selection with global CUR.

Make wfl cli CUR-global command able to calculate its own descriptors

---

wfl/fit/ace.py

Small changes to `wfl/fit/ace.py`, mainly to filename variables and logic.
Also remove `.keys()` from many instances of `if X in dict.keys()`.

clean up filename/path logic in ace1pack-update

---

wfl/scripts/ace_fit.jl

Current code converts fitting configs to list in `prepare_configs()`, but `run_ace_fit()` still tries to call the `to_memory()` method when preparing for a remote job.  PR removes the call to `to_memory()`, and documents that `run_ace_fit()` expects a _list_ of Atoms.
This would probably have been caught if we routinely ran the remote versions of the tests.

Fix bug in remote job ACE fit

---

wfl/autoparallelize/pool.py
wfl/cli/dft_convergence_test.py
wfl/cli/gap_rss_iter_fit.py

This behavior is now the default.  Changes all in cli files.
closes #80

Get rid of usage of all_or_none=True force=True

---

wfl/cli/gap_rss_iter_fit.py
wfl/configset.py

Create ConfigSet for defect confs with `input_configsets` instead of `input_configs`.
Also, actually make sure stored iterables are lists when `ConfigSet` gets `input_configs`.

Fix bug in creating ConfigSet for defect confs in do_MD_bulk_defect_step()

---

.github/workflows_assets/config.json
docs/source/examples.md.md
docs/source/examples.orca.md
tests/test_ace_fitting.py
tests/test_buildcell.py
tests/test_gap_fitting_multistage.py
tests/test_gap_fitting_simple.py
tests/test_remote_run.py
wfl/autoparallelize/base.py
wfl/autoparallelize/remote.py
wfl/autoparallelize/utils.py
wfl/fit/ace.py
wfl/fit/gap/multistage.py
wfl/fit/gap/simple.py
wfl/fit/utils.py

Replace routine-specific env vars with `RemoteInfo` dicts with values in `WFL_EXPYRE_INFO`.  
Refactor logic to get `remote_info` from `_autoparallelize_ll()` into `autoparallelize/utils.py::get_remote_info()`, so it can be used by other functions, and call it from all routines that need a `RemoteInfo` `kwargs` dict, in particular for now GAP and ACE fitting functions.

replace routine specific vars like WFL_GAP_SIMPLE_FIT_REMOTE_INFO, all use WFL_EXPYRE_INFO

---

.github/workflows/pytests.yml
tests/conftest.py
tests/test_calc_descriptor.py
tests/test_ref_error.py

Fix tests that fail when WFL_NUM_PYTHON_SUBPROCESSES > 1, and run with 2 as the default if env var is not already set

pytest with WFL_NUM_PYTHON_SUBPROCESSES > 1

---

wfl/autoparallelize/autoparainfo.py

@bernstei very quick bug fix - it used to be impossible to overwrite the AutoparaInfo defaults, set when parallelising a function. Please merge if this looks ok.

bug fix in autoparainfo

---

tests/test_autoparallelize.py
tests/test_buildcell.py
wfl/autoparallelize/__init__.py
wfl/calculators/dft.py
wfl/calculators/orca/__init__.py
wfl/calculators/orca/basinhopping.py
wfl/descriptors/quippy.py
wfl/generate/buildcell.py
wfl/generate/md.py
wfl/generate/optimize.py
wfl/generate/phonopy.py
wfl/generate/smiles.py
wfl/generate/supercells.py
wfl/generate/vib.py
wfl/select/simple.py

Rewrite the parallelized functions that have been working with `_autoparallelize_ll` to instead use `autoparallelize`, following `generic.py` example.

Update all parallelized functions to consistently use the new autoparallelize

---

docs/source/overview.configset.rst
examples/iterative_gap_fit/batch_gap_fit.py
examples/select_fps/fps.py
setup.py
tests/calculators/test_calc_generic.py
tests/test_calc_descriptor.py
tests/test_molecules.py
tests/test_optimize.py
tests/test_select_greedy_fps.py
wfl/autoparallelize/base.py
wfl/calculators/generic.py
wfl/descriptors/quippy.py
wfl/generate/buildcell.py
wfl/generate/md/__init__.py
wfl/generate/minimahopping.py
wfl/generate/optimize.py
wfl/generate/phonopy.py
wfl/generate/smiles.py
wfl/generate/supercells.py
wfl/generate/vib.py
wfl/select/simple.py

Much cleaner autoparallelize-wrapped docstring with `docstring_parse`. Just `wfl.descriptors.quippy.calc` so far.
Also clean up some `descriptors.quippy.calc()` syntax
closs #159

clean up autoparallelize wrapping docstring mangling

---

docs/source/conf.py

See https://github.com/spatialaudio/nbsphinx/issues/24#issuecomment-187172022

Try a workaround for missing syntax highlighting in nbsphinx redered notebook

---

wfl/cli/gap_rss_iter_fit.py

`buildcell.create_output` now returns string
`fit.error.calc` only computes errors, without evaluating with potential, and returns different quantities

Update gap_rss_iter_fit.py for recent changes to routines it uses

---

wfl/cli/gap_rss_iter_fit.py

Now that DFT evaluations are just done using `generic.run`, it's harder to specify their `RemoteInfo` from an env var with a dict key that points to the call stack and still distinguish them from other calls to `generic.run`, because more of the tail end of the call stack is identical. As a result, it's more useful to have (unique) remote_label arguments to the egeneric.run` calls that do the DFT evaluations, so add one to `gap_rss_iter_fit.py`.

Add a remote_label to the Vasp evaluation call in `gap_rss_iter_fit.py`.

---

wfl/autoparallelize/base.py

Have a better description than 
```
Returning before <function _sample_autopara_wrappable at 0x7f8e44077820> since output is done
```
Follows the "Running" reporting of operation name:
```
Running wfl.calculators.generic._run_autopara_wrappable with num_python_subprocesses=2, num_inputs_per_python_subprocess=10
```

Use full operation name when reporting autoparallelize status

---

complete_pytest.tin
docs/source/examples.daisy_chain_mlip_fitting.ipynb
tests/test_doc_examples.py
tests/test_md.py
tests/test_remote_run.py
wfl/autoparallelize/base.py
wfl/autoparallelize/pool.py
wfl/autoparallelize/remote.py
wfl/autoparallelize/utils.py
wfl/generate/md/__init__.py
wfl/generate/minimahopping.py
wfl/generate/optimize.py

Used to set per-item info, including number of config in overall sequence, as well as unique local rng seed, chosen well (hopefully) for parallel operation (see https://numpy.org/doc/stable/reference/random/parallel.html#sequence-of-integer-seeds).
Makes it possible to run deterministic  stochastic autopara ops (like md, for velocities, optimize, for random pressure, and minimahopping).

Autopara per item info

---

tests/test_remote_run.py
wfl/autoparallelize/autoparainfo.py
wfl/autoparallelize/base.py
wfl/autoparallelize/remote.py
wfl/autoparallelize/remoteinfo.py
wfl/autoparallelize/utils.py

Refactor `RemoteInfo` and `AutoparaInfo` related code so that all `AutoparaInfo` settings are applied to remote job, in particular `num_python_subprocesses`
Closes #216

pass AutoparaInfo settings to remote jobs

---

wfl/calculators/generic.py

I tried the branch out and run into problems:
1.  The `calculator` was either a `pickled_calculator` or `None`, so `calculator[0]` does not work. (I added a variable calculator_info, which is probably not the most elegant Solution.)
2.  Missing brackets for the construct_calculator_picklesafe.
This version is now working and tested on my setup.

Debug of per config calculator

---

tests/calculators/test_calc_generic.py
tests/calculators/test_vasp.py
tests/prep_test_cli_rss.sh

First trial, lets see if this works.

Per configuration pytest

---

docs/source/overview.configset.rst
docs/source/overview.parallelisation.rst
docs/source/overview.queued.md

Add warnings in the docs about ways the caching of information (output files from all autoparallelized operations and stage directories from expyre jobs) can fail if the source code that's being executed is changed.

Docs caching warning

---

.github/workflows/pytests.yml
complete_pytest.tin
wfl/autoparallelize/base.py
wfl/autoparallelize/remote.py
wfl/calculators/espresso.py
wfl/configset.py

Add `wait_for_results` argument to normal autoparallelized ops (not just fitting) so many can be started without blocking.
Wipe tmp.* files when creating `OutputSpec` so current practice of opening them for append (mode "a") will not lead to multiple copies of initial configs if script is stopped mid-op and rerun.
closes #281

wait_for_results and fix multiple copies of output configs when interrupted and restarted

---

complete_pytest.tin
setup.py
tests/calculators/test_vasp.py
tests/test_optimize.py
tests/test_remote_run.py
wfl/calculators/generic.py
wfl/calculators/utils.py

Change the way calculator results copying checks for DFT calculator convergence to be less Vasp specific. 
Add test for convergence status.

DFT calculator convergence test

---

.github/workflows/pytests.yml
README.md
complete_pytest.tin
docs/source/index.rst
setup.py
tests/test_configset.py
tests/test_remote_run.py
wfl/calculators/espresso.py
wfl/calculators/generic.py
wfl/configset.py

Test the Espresso calculator wrapper in a remote job

Add remote job test with an Espresso calculator evaluation

---

.github/workflows/docs.yml

further attempt to fix docs generated in github CI

Fix github CI workflow that generates docs

---

wfl/fit/mace.py

Make `foundations_model` mace fit param an absolute path before it's passed to `run_train.py` if it appears to be a file so that it'll work after a possible `os.chdir` into an explicitly selected `workdir`.

MACE fit fix handling of path for foundations_model when workdir is used

---

setup.py
wfl/fit/error.py

New location for `get_cmap`, in `matplotlib.pyplot` instead of `matplotlib.cm`

CI test fails to import get_cmap

---

wfl/fit/mace.py

Make sure that `wfl.mace.fit` does all its work in `workdir`.  In particular, move config scratch file creation into that directory.

do all of mace fit work in workdir

---

wfl/generate/smiles.py

Add nicer error message when trying to use wfl.generate.smiles if rdkit isn't installed
closes #315

unhelpful error if rdkit is not installed 

---

wfl/generate/md/__init__.py

Add optional `compressibility_au`.
Should this be simplified to do less for the user, and assume they know how to use ASE MD?

Add explicit compressibility arg (instead of calculating it) to wrapped MD

---

.github/workflows/pytests.yml
tests/calculators/test_ase_fileio_caching.py
tests/calculators/test_calc_generic.py
tests/calculators/test_vasp.py
tests/calculators/test_wrapped_calculator.py
wfl/calculators/generic.py

Code from Noam to check if ase calculators are executing multiple singlepoints.
Not tested because I don't have a vasp license.

Test for ase fileio caching with VASP example

---

wfl/fit/error.py

Return signed diffs and raw parity quantities (if scalar) from `wfl/fit/error.py`
closes #335

Try to fix sign of scalar diffs and parity quantities in error analysis

---

.github/workflows/pytests.yml
tests/test_configset.py
wfl/configset.py

Convenience operator to concatenate `ConfigSet` objects with `+`

Overload '+' operator to concatenate ConfigSet objects

---

wfl/autoparallelize/base.py

Treat `None` passed into `autopara_info` same as not passing anything at all, i.e. empty object

treat missing/None autopara_info and remote_info the same

---

wfl/configset.py

Explicitly test all files for existence, and globs for matching _something_, when creating a `ConfigSet`, and give meaningful error message if not.

better error message when ConfigSet is passed a nonexistent file/glob

---

tests/local_scripts/complete_pytest.tin
tests/test_list_with_nested_configset_info.py
wfl/autoparallelize/remote.py

Remove `"_ConfigSet_loc"` from `Atoms.info` in `do_remotely()` when iterable is not a `ConfigSet`
closes #344

Fix bug when Atoms.info["_ConfigSet_loc"] is present but iterable is not a ConfigSet

---

.github/workflows/pytests.yml
tests/test_error.py
tests/test_md.py
wfl/fit/error.py
wfl/fit/utils.py

Always do virial/stress error calculation in Voigt-6, so a, off-diagonal elements are always accounted for only once, and b, handle both 6 and 3x3 format reference and calculated quantities

Convert virial/stress to Voigt-6 when computing error table

---

.github/workflows/pytests.yml
tests/local_scripts/complete_pytest.tin
wfl/autoparallelize/remote.py

Fix _very_ subtle bug in remote jobs with an op that takes a `ConfigSet` as its basic input, rather than an `Atoms` object. 
The subtlety of this bug feels like a bad sign for the overall design, but the tiny fix suggests maybe it's OK
closes #349

fix bug with remote jobs for an op that takes a ConfigSet as its input

---

wfl/fit/mace.py

Added "ref_property_prefix", "verbose", and "dry_run" to remote_func_kwargs so that these arguments are passed when running remotely.

add arguments to remote_func_kwargs
