tests/calculators/test_orca.py
=> tests use ASE_ORCA_COMMAND instead of looking for `orca` in PATH

wfl/cli/gap_rss_iter_fit.py
Refactor reading of buildcell configs at each iter of gap_rss_iter_fit.py so that they can be step dependent.
=> make gap_rss_iter_fit.py buildcell configs step dependent

README.md
=> replace iterable_loop with autoparallelize in main README.md

.github/workflows/pytests.yml
avoid broken conda-forge packages.
=> Install phonopy and phono3py from github source

wfl/fit/ace.py
Optionally automatically generate `Atoms.info["config_type"]` and corresponding weights (in ACE params) from `*_sigma` `Atoms.info` fields for ace fit
=> enable wfl.fit.ace to use *_sigma to generate per-config weights

tests/calculators/test_basin_hopping_orca.py, tests/calculators/test_orca.py, tests/test_cli.py, wfl/calculators/orca/__init__.py, wfl/calculators/orca/basinhopping.py, wfl/calculators/wfl_fileio_calculator.py, wfl/cli/cli.py
Updated to be consistent with VASP and Espresso. Also updated the command line interface and corresponding test. Needs #161 to be resolved.
=> Orca calc update

tests/test_md.py, wfl/generate/md/__init__.py
=> in generate.md.sample() via the traj_select_during_func argument, require last image pass this filter too.

tests/test_buildcell.py, wfl/generate/buildcell.py
=> for generation via buildcell, let prep stage return a string and only optionally write to file

docs/source/examples.mlip_fitting.md
Not sure if this is the best way.
closes #182
=> Try to fix nesting levels in MLIP Fitting example

wfl/cli/commands/eval.py
I think that's it - please merge if looks ok.
=> added "ctx" where missing

.github/workflows/pytests.yml
Enable github CI ssh after slurm install failure to investigate
=> investigate failing CI slurm install

wfl/fit/ace.py
One more minor tweak to possible ways to set ACE weights.
=> ACE fit weights from global E/F/V times _one_ per-config quantity

wfl/generate/supercells.py
Optionally make largest bulk supercells with `ase.build.supercells.find_optimal_cell_shape`
=> Add ase_optimal optional bool to generate.supercells.largest_bulk

.github/workflows/docs.yml
@simonwengert do you think this should do it?
=> Add ipython to docs.yml for syntax highlighting

docs/source/examples.daisy_chain_mlip_fitting.ipynb, docs/source/examples.index.md, docs/source/examples.mlip_fitting.md, docs/source/examples.rst
This is broken link fix and small title updates, so will merge once tests pass.
=> Small doc fixes

.github/workflows/pytests.yml
Install MACE from github develop branch for testing purposes
=> Install MACE in CI

tests/calculators/test_vasp.py, wfl/calculators/vasp.py
Extend Vasp calculator to do multiple calculations in the same rundir with different parameters. Useful for doing, e.g., a converged GGA calculation and use WAVECAR to start hybrid functional.
Should perhaps be generalized for other calculators, but not entirely clear how yet.
=> Vasp multi calculation

complete_pytest.tin, tests/assets/mace_fit_parameters.yaml, wfl/fit/mace.py
Update mace fitting wrapper to use wrapper function args to set command line arguments. 
Corresponding update to tests
=> mace fit wrapper should use function args to set corresponding command line args

wfl/generate/optimize.py
Switch `ExpCellFilter` to `FrechetCellFilter`, and add stress_mask
Add "last" (not just "last_converged") as optimize traj_subselect method.
=> mask in cell minim and option to pick just last config from minim

complete_pytest.tin, tests/test_minimahopping.py, wfl/autoparallelize/pool.py, wfl/generate/minimahopping.py, wfl/generate/optimize.py
Pass `do_cell=False` to `FixSymmetry()` because it breaks calculation caching in PreconLBFGS
Also, clean up minimahopping tests
=> Don't adjust cell in optimize FixSymmetry because it breaks calculation caching in PreconLBFGS

complete_pytest.tin, setup.py, tests/test_optimize.py, wfl/configset.py, wfl/generate/optimize.py
Correctly test for matching `_ConfigSet_loc` so group iterator will work.
optimize no longer increases nesting level when `traj_subselect` indicates only one config from each traj (`"last"` or `"last_converged"`)
closes #287
=> Fix group iterator

tests/test_md.py, wfl/generate/md/abort.py
Add `generate.md.abort.AbortOnLowEnergy` md check
=> Check and exit when MD energy drops too much

wfl/cli/commands/eval.py
Update wfl cli eval for current MACECalculator (e.g. using `modelpaths`), and some additional cleanups.
=> wfl cli MACECalculator update

wfl/cli/cli_options.py, wfl/cli/commands/eval.py, wfl/generate/optimize.py
Add Calculator constructor kwargs to "wfl eval <potential> ..."
=> enable additional kwargs for "wfl eval <potential> ..."

.github/workflows/publish_to_pypi.yml, setup.py
Hi, second, rebase-accident free version of the PR for the PyPI release.
=> Add yml file for pypi workflow, change dependencies to PyPI releases

LICENSE
Add standard GPLv2 license as discussed in the Slack channel.
=> add standard GPLv2 license

tests/test_md.py, wfl/generate/md/__init__.py
refactor `wfl.generate.md.md` to allow for per-config temperature and pressure from `Atoms.info` fields `WFL_MD_TEMPERATURE` and `..._PRESSURE`
=> Enable per config md temperature and pressure
